# build.ps1 - bundles synchub.lua + steal_an_egg.lua into a single sae.lua
#
# The release file has to be self contained because loadstring(HttpGet(...))
# gives the script no filesystem and no second request. So the library is
# wrapped in a closure and handed to the feature file through
# ENV.SyncHubInline, which is the first thing loadLibrary() checks.
#
# Both source files stay independently runnable; nothing is rewritten, only
# wrapped. Run:  .\build.ps1

$ErrorActionPreference = "Stop"

$root    = $PSScriptRoot
$library = Join-Path $root "synchub.lua"
$feature = Join-Path $root "steal_an_egg.lua"
$output  = Join-Path $root "sae.lua"

foreach ($path in @($library, $feature)) {
    if (-not (Test-Path -LiteralPath $path)) {
        throw "missing source file: $path"
    }
}

$libraryBody = Get-Content -LiteralPath $library -Raw
$featureBody = Get-Content -LiteralPath $feature -Raw
$stamp       = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")

$header = @"
--!nonstrict
--[[
    sae.lua - SyncHub for Steal an Egg (generated bundle)

    Built $stamp by build.ps1. Do not edit this file; edit synchub.lua or
    steal_an_egg.lua and rebuild, or your changes are lost on the next build.

    Load with:
        loadstring(game:HttpGet("https://raw.githubusercontent.com/isynczxc/steal-an-eggers/main/sae.lua"))()
--]]

local ENV = (typeof(getgenv) == "function" and getgenv()) or _G

-- ==== synchub.lua (inlined) ==============================================
ENV.SyncHubInline = function()
"@

$middle = @"

end
-- ==== end synchub.lua ====================================================

-- ==== steal_an_egg.lua ===================================================
"@

$footer = @"

-- ==== end steal_an_egg.lua ===============================================
"@

$bundle = $header + "`n" + $libraryBody + $middle + "`n" + $featureBody + $footer

# LF endings and no BOM: some executors' loadstring chokes on a UTF-8 BOM.
$bundle = $bundle -replace "`r`n", "`n"
[System.IO.File]::WriteAllText($output, $bundle, (New-Object System.Text.UTF8Encoding $false))

$size = [math]::Round((Get-Item -LiteralPath $output).Length / 1KB, 1)
Write-Host "built sae.lua  ($size KB)"

# Compile check if a luau binary is on PATH or in the temp toolchain.
$luau = Get-Command "luau-compile" -ErrorAction SilentlyContinue
if (-not $luau) {
    $candidate = Join-Path $env:TEMP "opencode\luau\luau-compile.exe"
    if (Test-Path -LiteralPath $candidate) { $luau = $candidate }
}
if ($luau) {
    $exe = if ($luau -is [string]) { $luau } else { $luau.Source }
    $result = & $exe --null $output 2>&1 | Out-String
    if ($result -match "Error") { Write-Host "COMPILE FAILED`n$result" }
    else { Write-Host "compile ok" }
} else {
    Write-Host "luau-compile not found; skipped syntax check"
}
