--!nonstrict
--[[
    sae.lua - SyncHub for Steal an Egg (generated bundle)

    Built 2026-09-05 12:51:47 by build.ps1. Do not edit this file; edit synchub.lua or
    steal_an_egg.lua and rebuild, or your changes are lost on the next build.

    Load with:
        loadstring(game:HttpGet("https://raw.githubusercontent.com/isynczxc/steal-an-eggers/main/sae.lua"))()
--]]

local ENV = (typeof(getgenv) == "function" and getgenv()) or _G

-- ==== synchub.lua (inlined) ==============================================
ENV.SyncHubInline = function()
--!nonstrict
--[[
    synchub.lua - v2 UI framework. Yours end to end: no key, no remote fetch,
    no external library.

        local Hub = loadstring(readfile("SyncHub/synchub.lua"))()
        local win = Hub.new("SyncHub", "SyncHub/StealAnEgg")

        local tab = win:Tab("HOME", "Live")
        local box = tab:Group("Stats")
        box:Toggle("AutoSteal", "Auto Steal", false, function(on) end)
        box:Slider("StealSpeed", "Speed", 100, 1200, 960, 10, function(v) end)
        box:Dropdown("TargetPriority", "Priority", {"Rarity","KG"}, "Rarity", false, fn)
        box:Dropdown("TargetRarities", "Rarities", RARITIES, {}, true, fn)
        box:Input("Webhook", "URL", "", fn)
        box:Keybind("ToggleUI", "Menu", Enum.KeyCode.RightShift, fn)

    Every widget takes an `idx` as its first argument. That idx is the config
    key, so saving is automatic and renaming a label never breaks a saved file.

    Re-executing hot-reloads: the previous window is destroyed first.
--]]

local UserInputService = game:GetService("UserInputService")
local TweenService     = game:GetService("TweenService")
local HttpService      = game:GetService("HttpService")
local RunService       = game:GetService("RunService")
local Players          = game:GetService("Players")

local ENV = (typeof(getgenv) == "function" and getgenv()) or _G
local hasFS = isfile and readfile and writefile and isfolder and makefolder

local THEME = {
    bg      = Color3.fromRGB(18, 19, 24),
    panel   = Color3.fromRGB(24, 26, 32),
    bar     = Color3.fromRGB(28, 30, 37),
    row     = Color3.fromRGB(33, 35, 43),
    rowHi   = Color3.fromRGB(41, 44, 54),
    accent  = Color3.fromRGB(88, 214, 141),
    warn    = Color3.fromRGB(232, 176, 84),
    bad     = Color3.fromRGB(226, 98, 98),
    off     = Color3.fromRGB(58, 61, 72),
    text    = Color3.fromRGB(236, 238, 243),
    dim     = Color3.fromRGB(146, 152, 166),
    stroke  = Color3.fromRGB(44, 47, 57),
}

local TWEEN = TweenInfo.new(0.14, Enum.EasingStyle.Quad, Enum.EasingDirection.Out)

--------------------------------------------------------------------- helpers
local function create(class, props, parent)
    local inst = Instance.new(class)
    for k, v in props do
        inst[k] = v
    end
    if parent then inst.Parent = parent end
    return inst
end

local function corner(inst, radius)
    create("UICorner", { CornerRadius = UDim.new(0, radius or 6) }, inst)
    return inst
end

local function stroke(inst, colour, thickness)
    create("UIStroke", {
        Color = colour or THEME.stroke,
        Thickness = thickness or 1,
        ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
    }, inst)
    return inst
end

local function list(parent, padding)
    return create("UIListLayout", {
        Padding = UDim.new(0, padding or 5),
        SortOrder = Enum.SortOrder.LayoutOrder,
    }, parent)
end

local function pad(parent, all)
    return create("UIPadding", {
        PaddingLeft = UDim.new(0, all or 8), PaddingRight = UDim.new(0, all or 8),
        PaddingTop = UDim.new(0, all or 8), PaddingBottom = UDim.new(0, all or 8),
    }, parent)
end

local function label(parent, text, size, colour, bold)
    return create("TextLabel", {
        BackgroundTransparency = 1,
        Font = bold and Enum.Font.GothamBold or Enum.Font.Gotham,
        TextSize = size or 12,
        TextColor3 = colour or THEME.text,
        TextXAlignment = Enum.TextXAlignment.Left,
        TextTruncate = Enum.TextTruncate.AtEnd,
        Text = text,
    }, parent)
end

local function join(values)
    local parts = {}
    for value, on in values do
        if on then table.insert(parts, tostring(value)) end
    end
    table.sort(parts)
    return parts
end

--=========================================================================--
--                                 WINDOW                                  --
--=========================================================================--
local Window = {}
Window.__index = Window

function Window.new(title, dir)
    local self = setmetatable({}, Window)

    self.title       = title or "SyncHub"
    self.dir         = dir or "SyncHub"
    self.cfgDir      = self.dir .. "/configs"
    self.connections = {}
    self.loops       = {}
    self.widgets     = {}          -- idx -> widget handle
    self.tabs        = {}
    self.keybinds    = {}
    self.config      = {}
    self.activeTab   = nil
    self.order       = 0
    self.uiVisible   = true

    self:_ensureDirs()
    self.config = self:LoadConfig("default", true)
    self:_build()
    self:_bindHotkeys()
    return self
end

------------------------------------------------------------------- config io
function Window:_ensureDirs()
    if not hasFS then return end
    pcall(function()
        if not isfolder(self.dir) then makefolder(self.dir) end
        if not isfolder(self.cfgDir) then makefolder(self.cfgDir) end
    end)
end

function Window:_cfgPath(name)
    return self.cfgDir .. "/" .. (name or "default") .. ".json"
end

-- Reads a config file into a plain table. Does not apply it.
function Window:ReadConfig(name)
    if not hasFS then return {} end
    local path = self:_cfgPath(name)
    if not isfile(path) then return {} end
    local ok, raw = pcall(readfile, path)
    if not ok then return {} end
    local decoded, result = pcall(function() return HttpService:JSONDecode(raw) end)
    return (decoded and type(result) == "table") and result or {}
end

-- Loads a config. `quiet` skips pushing values into widgets, which is what the
-- constructor wants because no widgets exist yet.
function Window:LoadConfig(name, quiet)
    local data = self:ReadConfig(name)
    self.config = data
    self.configName = name or "default"
    if not quiet then
        for idx, widget in self.widgets do
            if data[idx] ~= nil and widget.Set then
                pcall(widget.Set, data[idx], true)
            end
        end
        self:Notify("Loaded config: " .. self.configName, "ok")
    end
    return data
end

function Window:SaveConfig(name)
    name = name or self.configName or "default"
    self.configName = name
    if not hasFS then return false end
    self:_ensureDirs()
    local ok = pcall(function()
        writefile(self:_cfgPath(name), HttpService:JSONEncode(self.config))
    end)
    if ok then self:Notify("Saved config: " .. name, "ok")
    else self:Notify("Save failed", "bad") end
    return ok
end

function Window:ListConfigs()
    local names = {}
    if not hasFS or not listfiles then return names end
    local ok, files = pcall(listfiles, self.cfgDir)
    if not ok then return names end
    for _, path in files do
        local name = string.match(path, "([^/\\]+)%.json$")
        if name then table.insert(names, name) end
    end
    table.sort(names)
    return names
end

-- Writes are debounced: dragging a slider fires Set on every frame and a
-- writefile per frame will stutter the client. One save, one second after the
-- last change wins.
function Window:Set(idx, value)
    self.config[idx] = value
    if not hasFS or self.autosave == false then return end

    self._saveToken = (self._saveToken or 0) + 1
    local token = self._saveToken
    task.delay(1, function()
        if self._saveToken ~= token then return end
        pcall(function()
            writefile(self:_cfgPath(self.configName or "default"),
                HttpService:JSONEncode(self.config))
        end)
    end)
end

function Window:Get(idx, fallback)
    local value = self.config[idx]
    return value == nil and fallback or value
end

------------------------------------------------------------------- lifetime
function Window:Track(connection)
    table.insert(self.connections, connection)
    return connection
end

-- A loop bound to the window's lifetime. Returns a stop function.
-- `guard` is checked every tick; when it returns false the body is skipped
-- without killing the loop, which is how toggles gate their workers.
function Window:Loop(interval, fn, guard)
    local alive = true
    table.insert(self.loops, function() alive = false end)
    task.spawn(function()
        while alive do
            if not guard or guard() then
                local ok, err = pcall(fn)
                if not ok then warn("[SyncHub] loop: " .. tostring(err)) end
            end
            task.wait(interval)
        end
    end)
    return function() alive = false end
end

function Window:Destroy()
    for _, stop in self.loops do pcall(stop) end
    for _, c in self.connections do pcall(function() c:Disconnect() end) end
    self.loops, self.connections = {}, {}
    if self.onDestroy then pcall(self.onDestroy) end
    if self.gui then pcall(function() self.gui:Destroy() end) end
    if ENV.SyncHub == self then ENV.SyncHub = nil end
end

--------------------------------------------------------------------- build
function Window:_parent()
    if gethui then
        local ok, hidden = pcall(gethui)
        if ok and hidden then return hidden end
    end
    local ok, coreGui = pcall(function() return game:GetService("CoreGui") end)
    if ok and coreGui then return coreGui end
    return Players.LocalPlayer:WaitForChild("PlayerGui")
end

function Window:_build()
    self.gui = create("ScreenGui", {
        Name           = "SyncHub_" .. tostring(math.random(1e5, 1e6)),
        IgnoreGuiInset = true,
        ResetOnSpawn   = false,
        DisplayOrder   = 999,
        ZIndexBehavior = Enum.ZIndexBehavior.Sibling,
    }, self:_parent())

    local root = corner(create("Frame", {
        Name = "Window",
        AnchorPoint = Vector2.new(0.5, 0.5),
        Position = UDim2.fromScale(0.5, 0.5),
        Size = UDim2.fromOffset(520, 420),
        BackgroundColor3 = THEME.bg,
        BorderSizePixel = 0,
        Active = true,
        ClipsDescendants = true,
    }, self.gui), 10)
    stroke(root)
    self.root = root

    -- title bar ---------------------------------------------------------
    local bar = create("Frame", {
        Name = "TitleBar", Size = UDim2.new(1, 0, 0, 38),
        BackgroundColor3 = THEME.bar, BorderSizePixel = 0,
    }, root)

    create("Frame", {
        Size = UDim2.new(1, 0, 0, 1), Position = UDim2.new(0, 0, 1, -1),
        BackgroundColor3 = THEME.stroke, BorderSizePixel = 0,
    }, bar)

    local titleLabel = label(bar, self.title, 14, THEME.text, true)
    titleLabel.Position = UDim2.fromOffset(13, 0)
    titleLabel.Size = UDim2.new(0, 160, 1, 0)

    self.status = label(bar, "", 11, THEME.dim)
    self.status.Position = UDim2.new(0, 180, 0, 0)
    self.status.Size = UDim2.new(1, -250, 1, 0)

    local function barButton(offset, text, colour)
        local button = corner(create("TextButton", {
            AutoButtonColor = false,
            Position = UDim2.new(1, offset, 0.5, -11),
            Size = UDim2.fromOffset(24, 22),
            BackgroundColor3 = THEME.row, BorderSizePixel = 0,
            Font = Enum.Font.GothamBold, TextSize = 14,
            TextColor3 = colour or THEME.dim, Text = text,
        }, bar), 5)
        return button
    end

    local closeButton    = barButton(-30, "x", THEME.bad)
    local minimiseButton = barButton(-60, "-")

    -- tab rail ----------------------------------------------------------
    local rail = create("ScrollingFrame", {
        Name = "Tabs",
        Position = UDim2.fromOffset(0, 38), Size = UDim2.new(1, 0, 0, 34),
        BackgroundColor3 = THEME.panel, BorderSizePixel = 0,
        CanvasSize = UDim2.new(),
        AutomaticCanvasSize = Enum.AutomaticSize.X,
        ScrollBarThickness = 0,
        ScrollingDirection = Enum.ScrollingDirection.X,
    }, root)
    create("UIListLayout", {
        FillDirection = Enum.FillDirection.Horizontal,
        Padding = UDim.new(0, 4),
        SortOrder = Enum.SortOrder.LayoutOrder,
        VerticalAlignment = Enum.VerticalAlignment.Center,
    }, rail)
    create("UIPadding", {
        PaddingLeft = UDim.new(0, 8), PaddingRight = UDim.new(0, 8),
    }, rail)
    create("Frame", {
        Size = UDim2.new(1, 0, 0, 1), Position = UDim2.new(0, 0, 1, -1),
        BackgroundColor3 = THEME.stroke, BorderSizePixel = 0, ZIndex = 2,
    }, rail)
    self.rail = rail

    -- page host ---------------------------------------------------------
    self.pages = create("Frame", {
        Name = "Pages",
        Position = UDim2.fromOffset(0, 72), Size = UDim2.new(1, 0, 1, -72),
        BackgroundTransparency = 1,
    }, root)

    -- toasts ------------------------------------------------------------
    self.toasts = create("Frame", {
        Name = "Toasts",
        AnchorPoint = Vector2.new(1, 1),
        Position = UDim2.new(1, -12, 1, -12),
        Size = UDim2.fromOffset(250, 300),
        BackgroundTransparency = 1,
    }, self.gui)
    create("UIListLayout", {
        Padding = UDim.new(0, 6),
        SortOrder = Enum.SortOrder.LayoutOrder,
        VerticalAlignment = Enum.VerticalAlignment.Bottom,
        HorizontalAlignment = Enum.HorizontalAlignment.Right,
    }, self.toasts)

    -- mobile reopen bubble ----------------------------------------------
    local bubble = corner(create("TextButton", {
        Name = "Reopen", AutoButtonColor = false, Visible = false,
        Position = UDim2.fromScale(0.02, 0.4), Size = UDim2.fromOffset(44, 44),
        BackgroundColor3 = THEME.accent, BorderSizePixel = 0,
        Font = Enum.Font.GothamBold, TextSize = 17,
        TextColor3 = THEME.bg, Text = "S",
    }, self.gui), 22)
    self.bubble = bubble

    self:Track(minimiseButton.MouseButton1Click:Connect(function()
        self:SetVisible(false)
    end))
    self:Track(bubble.MouseButton1Click:Connect(function()
        self:SetVisible(true)
    end))
    self:Track(closeButton.MouseButton1Click:Connect(function()
        self:Destroy()
    end))

    self:_drag(bar, root)
    self:_drag(bubble, bubble)
end

function Window:SetVisible(visible)
    self.uiVisible = visible and true or false
    self.root.Visible = self.uiVisible
    self.bubble.Visible = not self.uiVisible
end

function Window:ToggleVisible()
    self:SetVisible(not self.uiVisible)
end

function Window:SetStatus(text, colour)
    if not self.status then return end
    self.status.Text = tostring(text or "")
    self.status.TextColor3 = colour or THEME.dim
end

-- Touch and mouse both route through InputBegan/InputChanged.
function Window:_drag(handle, target)
    local dragging, origin, startPos = false, nil, nil

    self:Track(handle.InputBegan:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1
            or input.UserInputType == Enum.UserInputType.Touch then
            dragging, origin, startPos = true, input.Position, target.Position
            self:Track(input.Changed:Connect(function()
                if input.UserInputState == Enum.UserInputState.End then
                    dragging = false
                end
            end))
        end
    end))

    self:Track(UserInputService.InputChanged:Connect(function(input)
        if not dragging then return end
        if input.UserInputType == Enum.UserInputType.MouseMovement
            or input.UserInputType == Enum.UserInputType.Touch then
            local delta = input.Position - origin
            target.Position = UDim2.new(
                startPos.X.Scale, startPos.X.Offset + delta.X,
                startPos.Y.Scale, startPos.Y.Offset + delta.Y)
        end
    end))
end

function Window:_bindHotkeys()
    self:Track(UserInputService.InputBegan:Connect(function(input, processed)
        if processed then return end
        if input.UserInputType ~= Enum.UserInputType.Keyboard then return end
        for _, bind in self.keybinds do
            if bind.key == input.KeyCode then
                pcall(bind.fn)
            end
        end
    end))
end

--=========================================================================--
--                              TABS & GROUPS                              --
--=========================================================================--
local Tab, Group = {}, {}
Tab.__index, Group.__index = Tab, Group

function Window:Tab(name)
    local win = self
    local self = setmetatable({}, Tab)
    self.win, self.name, self.order = win, name, #win.tabs + 1

    self.button = corner(create("TextButton", {
        Name = name, AutoButtonColor = false,
        Size = UDim2.fromOffset(math.max(58, #name * 8 + 20), 24),
        LayoutOrder = self.order,
        BackgroundColor3 = THEME.row, BorderSizePixel = 0,
        Font = Enum.Font.GothamMedium, TextSize = 12,
        TextColor3 = THEME.dim, Text = name,
    }, win.rail), 5)

    self.page = create("ScrollingFrame", {
        Name = name .. "Page", Visible = false,
        Size = UDim2.fromScale(1, 1),
        BackgroundTransparency = 1, BorderSizePixel = 0,
        CanvasSize = UDim2.new(),
        AutomaticCanvasSize = Enum.AutomaticSize.Y,
        ScrollBarThickness = 3,
        ScrollBarImageColor3 = THEME.off,
    }, win.pages)
    list(self.page, 7)
    pad(self.page, 10)

    win:Track(self.button.MouseButton1Click:Connect(function()
        win:Select(name)
    end))

    win.tabs[name] = self
    if not win.activeTab then win:Select(name) end
    return self
end

function Window:Select(name)
    for tabName, tab in self.tabs do
        local active = tabName == name
        tab.page.Visible = active
        TweenService:Create(tab.button, TWEEN, {
            BackgroundColor3 = active and THEME.accent or THEME.row,
        }):Play()
        tab.button.TextColor3 = active and THEME.bg or THEME.dim
    end
    self.activeTab = name
end

-- A collapsible titled container. The collapsed state persists per title.
function Tab:Group(title, collapsed)
    local tab = self
    local win = tab.win
    local self = setmetatable({}, Group)
    self.win, self.title = win, title

    tab.groupCount = (tab.groupCount or 0) + 1

    local key = "__group_" .. tab.name .. "_" .. title
    local isCollapsed = win:Get(key, collapsed and true or false)

    local frame = corner(create("Frame", {
        Name = title,
        Size = UDim2.new(1, 0, 0, 0),
        AutomaticSize = Enum.AutomaticSize.Y,
        BackgroundColor3 = THEME.panel, BorderSizePixel = 0,
        LayoutOrder = tab.groupCount,
        ClipsDescendants = true,
    }, tab.page), 8)
    stroke(frame)
    self.frame = frame

    local header = create("TextButton", {
        Name = "Header", AutoButtonColor = false,
        Size = UDim2.new(1, 0, 0, 30),
        BackgroundTransparency = 1, Text = "",
    }, frame)

    local titleLabel = label(header, title, 12, THEME.text, true)
    titleLabel.Position = UDim2.fromOffset(10, 0)
    titleLabel.Size = UDim2.new(1, -40, 1, 0)

    local chevron = label(header, isCollapsed and "+" or "-", 15, THEME.dim, true)
    chevron.Position = UDim2.new(1, -24, 0, 0)
    chevron.Size = UDim2.fromOffset(16, 30)
    chevron.TextXAlignment = Enum.TextXAlignment.Center

    local body = create("Frame", {
        Name = "Body", Visible = not isCollapsed,
        Position = UDim2.fromOffset(0, 30),
        Size = UDim2.new(1, 0, 0, 0),
        AutomaticSize = Enum.AutomaticSize.Y,
        BackgroundTransparency = 1,
    }, frame)
    list(body, 5)
    create("UIPadding", {
        PaddingLeft = UDim.new(0, 8), PaddingRight = UDim.new(0, 8),
        PaddingBottom = UDim.new(0, 8),
    }, body)
    self.body = body
    self.order = 0

    -- The frame auto-sizes from its children, so collapsing means hiding the
    -- body and pinning the height to the header.
    local function render()
        body.Visible = not isCollapsed
        chevron.Text = isCollapsed and "+" or "-"
        frame.AutomaticSize = isCollapsed and Enum.AutomaticSize.None
            or Enum.AutomaticSize.Y
        if isCollapsed then frame.Size = UDim2.new(1, 0, 0, 30) end
    end

    win:Track(header.MouseButton1Click:Connect(function()
        isCollapsed = not isCollapsed
        win:Set(key, isCollapsed)
        render()
    end))

    render()
    return self
end

function Group:_next()
    self.order += 1
    return self.order
end

function Group:_row(height)
    return corner(create("Frame", {
        Size = UDim2.new(1, 0, 0, height or 32),
        LayoutOrder = self:_next(),
        BackgroundColor3 = THEME.row, BorderSizePixel = 0,
    }, self.body), 5)
end

-- Registers a widget so config load can push values back into the UI.
function Group:_register(idx, handle)
    if idx then self.win.widgets[idx] = handle end
    return handle
end

function Group:_fail(idx, err)
    warn("[SyncHub] " .. tostring(idx) .. ": " .. tostring(err))
    self.win:SetStatus("error in " .. tostring(idx), THEME.bad)
end

--------------------------------------------------------------------- widgets
function Group:Label(text)
    local widget = label(self.body, text, 12, THEME.dim)
    widget.Size = UDim2.new(1, 0, 0, 0)
    widget.AutomaticSize = Enum.AutomaticSize.Y
    widget.TextWrapped = true
    widget.TextTruncate = Enum.TextTruncate.None
    widget.LayoutOrder = self:_next()
    return {
        Instance = widget,
        Set = function(value) widget.Text = tostring(value) end,
    }
end

function Group:Divider()
    local line = create("Frame", {
        Size = UDim2.new(1, 0, 0, 1), LayoutOrder = self:_next(),
        BackgroundColor3 = THEME.stroke, BorderSizePixel = 0,
    }, self.body)
    return line
end

function Group:Button(text, callback)
    local button = corner(create("TextButton", {
        Name = text, AutoButtonColor = false,
        Size = UDim2.new(1, 0, 0, 30), LayoutOrder = self:_next(),
        BackgroundColor3 = THEME.row, BorderSizePixel = 0,
        Font = Enum.Font.GothamMedium, TextSize = 12,
        TextColor3 = THEME.text, Text = text,
    }, self.body), 5)

    self.win:Track(button.MouseEnter:Connect(function()
        TweenService:Create(button, TWEEN, { BackgroundColor3 = THEME.rowHi }):Play()
    end))
    self.win:Track(button.MouseLeave:Connect(function()
        TweenService:Create(button, TWEEN, { BackgroundColor3 = THEME.row }):Play()
    end))
    self.win:Track(button.MouseButton1Click:Connect(function()
        local ok, err = pcall(callback)
        if not ok then self:_fail(text, err) end
    end))
    return button
end

function Group:Toggle(idx, text, default, callback)
    local win = self.win
    local saved = win:Get(idx)
    local state = if type(saved) == "boolean" then saved else (default or false)

    local row = self:_row(32)
    local name = label(row, text, 12, THEME.text)
    name.Position = UDim2.fromOffset(10, 0)
    name.Size = UDim2.new(1, -62, 1, 0)

    local track = corner(create("Frame", {
        Position = UDim2.new(1, -48, 0.5, -10), Size = UDim2.fromOffset(38, 20),
        BackgroundColor3 = THEME.off, BorderSizePixel = 0,
    }, row), 10)
    local knob = corner(create("Frame", {
        Position = UDim2.fromOffset(3, 3), Size = UDim2.fromOffset(14, 14),
        BackgroundColor3 = THEME.text, BorderSizePixel = 0,
    }, track), 7)

    local hit = create("TextButton", {
        BackgroundTransparency = 1, Text = "",
        Size = UDim2.fromScale(1, 1), ZIndex = 3,
    }, row)

    local function render(animate)
        local info = animate and TWEEN or TweenInfo.new(0)
        TweenService:Create(track, info, {
            BackgroundColor3 = state and THEME.accent or THEME.off,
        }):Play()
        TweenService:Create(knob, info, {
            Position = state and UDim2.fromOffset(21, 3) or UDim2.fromOffset(3, 3),
        }):Play()
    end

    local function apply(animate, silent)
        render(animate)
        win:Set(idx, state)
        if not silent and callback then
            local ok, err = pcall(callback, state)
            if not ok then self:_fail(idx, err) end
        end
    end

    win:Track(hit.MouseButton1Click:Connect(function()
        state = not state
        apply(true)
    end))

    render(false)
    -- Fire once on construction so a saved "on" state actually starts its worker.
    task.defer(function()
        if callback then
            local ok, err = pcall(callback, state)
            if not ok then self:_fail(idx, err) end
        end
    end)

    return self:_register(idx, {
        Instance = row,
        Get = function() return state end,
        Set = function(value, silent)
            state = value and true or false
            apply(true, silent)
        end,
    })
end

function Group:Slider(idx, text, min, max, default, step, callback)
    local win = self.win
    step = step or 1
    local saved = tonumber(win:Get(idx))
    local value = math.clamp(saved or default or min, min, max)

    local row = self:_row(44)
    local name = label(row, text, 12, THEME.text)
    name.Position = UDim2.fromOffset(10, 2)
    name.Size = UDim2.new(1, -80, 0, 18)

    local readout = label(row, tostring(value), 12, THEME.accent, true)
    readout.Position = UDim2.new(1, -74, 0, 2)
    readout.Size = UDim2.fromOffset(64, 18)
    readout.TextXAlignment = Enum.TextXAlignment.Right

    local bar = corner(create("Frame", {
        Position = UDim2.fromOffset(10, 26), Size = UDim2.new(1, -20, 0, 8),
        BackgroundColor3 = THEME.off, BorderSizePixel = 0,
    }, row), 4)
    local fill = corner(create("Frame", {
        Size = UDim2.fromScale((value - min) / math.max(max - min, 1), 1),
        BackgroundColor3 = THEME.accent, BorderSizePixel = 0,
    }, bar), 4)

    local function setFromScale(scale, silent)
        local raw = min + (max - min) * math.clamp(scale, 0, 1)
        local snapped = math.clamp(math.floor(raw / step + 0.5) * step, min, max)
        if snapped == value and not silent then return end
        value = snapped
        readout.Text = tostring(value)
        fill.Size = UDim2.fromScale((value - min) / math.max(max - min, 1), 1)
        win:Set(idx, value)
        if not silent and callback then
            local ok, err = pcall(callback, value)
            if not ok then self:_fail(idx, err) end
        end
    end

    local dragging = false
    local function track(input)
        local scale = (input.Position.X - bar.AbsolutePosition.X)
            / math.max(bar.AbsoluteSize.X, 1)
        setFromScale(scale)
    end

    win:Track(bar.InputBegan:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1
            or input.UserInputType == Enum.UserInputType.Touch then
            dragging = true
            track(input)
        end
    end))
    win:Track(UserInputService.InputEnded:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1
            or input.UserInputType == Enum.UserInputType.Touch then
            dragging = false
        end
    end))
    win:Track(UserInputService.InputChanged:Connect(function(input)
        if dragging and (input.UserInputType == Enum.UserInputType.MouseMovement
            or input.UserInputType == Enum.UserInputType.Touch) then
            track(input)
        end
    end))

    task.defer(function()
        if callback then pcall(callback, value) end
    end)

    return self:_register(idx, {
        Instance = row,
        Get = function() return value end,
        Set = function(newValue, silent)
            setFromScale(((tonumber(newValue) or min) - min) / math.max(max - min, 1), silent)
        end,
    })
end

function Group:Input(idx, text, default, callback)
    local win = self.win
    local value = tostring(win:Get(idx, default or ""))

    local row = self:_row(48)
    local name = label(row, text, 12, THEME.text)
    name.Position = UDim2.fromOffset(10, 2)
    name.Size = UDim2.new(1, -20, 0, 16)

    local box = corner(create("TextBox", {
        Position = UDim2.fromOffset(10, 22), Size = UDim2.new(1, -20, 0, 20),
        BackgroundColor3 = THEME.bg, BorderSizePixel = 0,
        Font = Enum.Font.Gotham, TextSize = 12,
        TextColor3 = THEME.text, TextXAlignment = Enum.TextXAlignment.Left,
        PlaceholderText = "...", PlaceholderColor3 = THEME.dim,
        ClearTextOnFocus = false, Text = value,
    }, row), 4)
    create("UIPadding", { PaddingLeft = UDim.new(0, 6) }, box)

    win:Track(box.FocusLost:Connect(function()
        value = box.Text
        win:Set(idx, value)
        if callback then
            local ok, err = pcall(callback, value)
            if not ok then self:_fail(idx, err) end
        end
    end))

    return self:_register(idx, {
        Instance = row,
        Get = function() return value end,
        Set = function(newValue, silent)
            value = tostring(newValue or "")
            box.Text = value
            win:Set(idx, value)
            if not silent and callback then pcall(callback, value) end
        end,
    })
end

-- multi=false -> value is a string. multi=true -> value is { option = true }.
function Group:Dropdown(idx, text, options, default, multi, callback)
    local win = self.win
    local saved = win:Get(idx)
    local value
    if multi then
        value = type(saved) == "table" and saved or {}
        if type(default) == "table" and saved == nil then
            for k, v in default do value[k] = v end
        end
    else
        value = type(saved) == "string" and saved or (default or options[1])
    end

    local row = self:_row(32)
    local name = label(row, text, 12, THEME.text)
    name.Position = UDim2.fromOffset(10, 0)
    name.Size = UDim2.new(0.45, -10, 1, 0)

    local summary = label(row, "", 11, THEME.accent)
    summary.Position = UDim2.new(0.45, 0, 0, 0)
    summary.Size = UDim2.new(0.55, -28, 1, 0)
    summary.TextXAlignment = Enum.TextXAlignment.Right

    local chevron = label(row, "v", 11, THEME.dim, true)
    chevron.Position = UDim2.new(1, -20, 0, 0)
    chevron.Size = UDim2.fromOffset(14, 32)

    local hit = create("TextButton", {
        BackgroundTransparency = 1, Text = "",
        Size = UDim2.fromScale(1, 1), ZIndex = 3,
    }, row)

    local menu = corner(create("Frame", {
        Visible = false,
        Size = UDim2.new(1, 0, 0, 0),
        AutomaticSize = Enum.AutomaticSize.Y,
        LayoutOrder = self:_next(),
        BackgroundColor3 = THEME.bg, BorderSizePixel = 0,
    }, self.body), 5)
    stroke(menu)
    local menuList = create("ScrollingFrame", {
        Size = UDim2.new(1, 0, 0, 0),
        AutomaticSize = Enum.AutomaticSize.Y,
        BackgroundTransparency = 1, BorderSizePixel = 0,
        CanvasSize = UDim2.new(), ScrollBarThickness = 2,
        ScrollBarImageColor3 = THEME.off,
    }, menu)
    list(menuList, 2)
    pad(menuList, 4)

    local function describe()
        if multi then
            local picked = join(value)
            summary.Text = #picked == 0 and "none"
                or (#picked <= 2 and table.concat(picked, ", ")
                or (#picked .. " selected"))
        else
            summary.Text = tostring(value)
        end
    end

    local rows = {}
    local function renderRows()
        for option, entry in rows do
            local on = if multi then value[option] == true else value == option
            entry.tick.BackgroundColor3 = on and THEME.accent or THEME.off
            entry.text.TextColor3 = on and THEME.text or THEME.dim
        end
        describe()
    end

    for order, option in options do
        local entry = corner(create("TextButton", {
            Name = tostring(option), AutoButtonColor = false,
            Size = UDim2.new(1, 0, 0, 24), LayoutOrder = order,
            BackgroundColor3 = THEME.row, BorderSizePixel = 0, Text = "",
        }, menuList), 4)

        local tick = corner(create("Frame", {
            Position = UDim2.fromOffset(6, 7), Size = UDim2.fromOffset(10, 10),
            BackgroundColor3 = THEME.off, BorderSizePixel = 0,
        }, entry), 3)

        local entryText = label(entry, tostring(option), 11, THEME.dim)
        entryText.Position = UDim2.fromOffset(24, 0)
        entryText.Size = UDim2.new(1, -30, 1, 0)

        rows[option] = { tick = tick, text = entryText }

        win:Track(entry.MouseButton1Click:Connect(function()
            if multi then
                value[option] = not value[option] or nil
            else
                value = option
                menu.Visible = false
                chevron.Text = "v"
            end
            win:Set(idx, value)
            renderRows()
            if callback then
                local ok, err = pcall(callback, value)
                if not ok then self:_fail(idx, err) end
            end
        end))
    end

    win:Track(hit.MouseButton1Click:Connect(function()
        menu.Visible = not menu.Visible
        chevron.Text = menu.Visible and "^" or "v"
    end))

    renderRows()
    task.defer(function()
        if callback then pcall(callback, value) end
    end)

    return self:_register(idx, {
        Instance = row,
        Get = function() return value end,
        Set = function(newValue, silent)
            value = newValue
            win:Set(idx, value)
            renderRows()
            if not silent and callback then pcall(callback, value) end
        end,
    })
end

function Group:Keybind(idx, text, default, callback)
    local win = self.win
    local savedName = win:Get(idx)
    local key = (savedName and Enum.KeyCode[savedName]) or default

    local row = self:_row(32)
    local name = label(row, text, 12, THEME.text)
    name.Position = UDim2.fromOffset(10, 0)
    name.Size = UDim2.new(1, -110, 1, 0)

    local button = corner(create("TextButton", {
        AutoButtonColor = false,
        Position = UDim2.new(1, -96, 0.5, -11), Size = UDim2.fromOffset(86, 22),
        BackgroundColor3 = THEME.bg, BorderSizePixel = 0,
        Font = Enum.Font.GothamMedium, TextSize = 11,
        TextColor3 = THEME.accent, Text = key and key.Name or "none",
    }, row), 4)

    local bind = { key = key, fn = callback }
    table.insert(win.keybinds, bind)

    local listening = false
    win:Track(button.MouseButton1Click:Connect(function()
        listening = true
        button.Text = "press..."
    end))
    win:Track(UserInputService.InputBegan:Connect(function(input, processed)
        if not listening then return end
        if input.UserInputType ~= Enum.UserInputType.Keyboard then return end
        listening = false
        if input.KeyCode == Enum.KeyCode.Escape then
            bind.key = nil
            button.Text = "none"
            win:Set(idx, nil)
            return
        end
        bind.key = input.KeyCode
        button.Text = input.KeyCode.Name
        win:Set(idx, input.KeyCode.Name)
    end))

    return self:_register(idx, {
        Instance = row,
        Get = function() return bind.key end,
        Set = function(newValue)
            local newKey = type(newValue) == "string" and Enum.KeyCode[newValue] or newValue
            bind.key = newKey
            button.Text = newKey and newKey.Name or "none"
        end,
    })
end

--=========================================================================--
--                          TOASTS & OVERLAY HUD                           --
--=========================================================================--
function Window:Notify(text, kind, duration)
    if not self.toasts then return end
    local colour = kind == "ok" and THEME.accent
        or kind == "bad" and THEME.bad
        or kind == "warn" and THEME.warn
        or THEME.dim

    local toast = corner(create("Frame", {
        Size = UDim2.new(1, 0, 0, 0),
        AutomaticSize = Enum.AutomaticSize.Y,
        BackgroundColor3 = THEME.bar, BorderSizePixel = 0,
        BackgroundTransparency = 1,
    }, self.toasts), 6)
    stroke(toast, colour)

    create("Frame", {
        Size = UDim2.new(0, 3, 1, 0), BackgroundColor3 = colour,
        BorderSizePixel = 0, ZIndex = 2,
    }, toast)

    local body = label(toast, tostring(text), 12, THEME.text)
    body.Position = UDim2.fromOffset(11, 0)
    body.Size = UDim2.new(1, -20, 0, 0)
    body.AutomaticSize = Enum.AutomaticSize.Y
    body.TextWrapped = true
    body.TextTruncate = Enum.TextTruncate.None
    create("UIPadding", {
        PaddingTop = UDim.new(0, 8), PaddingBottom = UDim.new(0, 8),
    }, toast)

    TweenService:Create(toast, TWEEN, { BackgroundTransparency = 0 }):Play()
    task.delay(duration or 3.5, function()
        TweenService:Create(toast, TWEEN, { BackgroundTransparency = 1 }):Play()
        body.TextTransparency = 1
        task.wait(0.2)
        pcall(function() toast:Destroy() end)
    end)
end

-- A small always-on-top readout, separate from the main window so it survives
-- the menu being closed. Lines are keyed so workers can update them cheaply.
function Window:Overlay(enabled)
    if not enabled then
        if self.overlay then self.overlay.Visible = false end
        return
    end
    if self.overlay then
        self.overlay.Visible = true
        return
    end

    local frame = corner(create("Frame", {
        Name = "Overlay",
        Position = UDim2.fromOffset(12, 12),
        Size = UDim2.fromOffset(190, 0),
        AutomaticSize = Enum.AutomaticSize.Y,
        BackgroundColor3 = THEME.bg, BackgroundTransparency = 0.15,
        BorderSizePixel = 0, Active = true,
    }, self.gui), 8)
    stroke(frame)
    list(frame, 2)
    pad(frame, 8)
    self.overlay = frame
    self.overlayLines = {}
    self:_drag(frame, frame)

    local header = label(frame, self.title, 12, THEME.accent, true)
    header.Size = UDim2.new(1, 0, 0, 16)
    header.LayoutOrder = 0
    return frame
end

function Window:OverlaySet(key, text)
    if not self.overlay then return end
    local line = self.overlayLines[key]
    if not line then
        line = label(self.overlay, "", 11, THEME.dim)
        line.Size = UDim2.new(1, 0, 0, 14)
        line.LayoutOrder = #self.overlayLines + 1
        self.overlayLines[key] = line
    end
    line.Text = tostring(text)
end

--=========================================================================--
--                                 EXPORT                                  --
--=========================================================================--
if ENV.SyncHub then
    pcall(function() ENV.SyncHub:Destroy() end)
    ENV.SyncHub = nil
end

return {
    new    = function(title, dir)
        local win = Window.new(title, dir)
        ENV.SyncHub = win
        return win
    end,
    THEME  = THEME,
    create = create,
    corner = corner,
}

end
-- ==== end synchub.lua ====================================================

-- ==== steal_an_egg.lua ===================================================
--!nonstrict
--[[
    steal_an_egg.lua - SyncHub feature set for Steal an Egg.

    Needs synchub.lua next to it (or at SyncHub/synchub.lua). No key, no
    remote fetch, nothing phones home except the Discord webhook you supply.

    Design note: this file never hardcodes remote names. Roblox games rename
    and reshuffle remotes constantly, so instead there is an Adapter that
    discovers them at runtime plus a Remote Logger that records what the game
    actually fires when you play manually. You bind a logged call to an action
    once, it saves to config, and every automation loop uses that binding.
    That is why nothing here breaks on a game update.
--]]

local Players            = game:GetService("Players")
local ReplicatedStorage  = game:GetService("ReplicatedStorage")
local RunService         = game:GetService("RunService")
local TeleportService    = game:GetService("TeleportService")
local HttpService        = game:GetService("HttpService")
local Lighting           = game:GetService("Lighting")
local VirtualUser        = game:GetService("VirtualUser")

local ENV   = (typeof(getgenv) == "function" and getgenv()) or _G
local hasFS = isfile and readfile and writefile

local DIR  = "SyncHub"
local REPO = "https://raw.githubusercontent.com/isynczxc/steal-an-eggers/main/"

--------------------------------------------------------------------- library
-- Three ways in, tried in order:
--   1. ENV.SyncHubInline - set by build.ps1 in the single-file release. This is
--      what runs when someone loadstrings sae.lua off GitHub.
--   2. a local file - what runs while you are editing.
--   3. HttpGet from the repo - fallback if only this file was loaded.
-- Nothing is cached, so editing synchub.lua and re-executing picks up the
-- change instead of serving a stale copy.
local function loadLibrary()
    if type(ENV.SyncHubInline) == "function" then
        return ENV.SyncHubInline()
    end

    for _, path in { DIR .. "/synchub.lua", "synchub.lua" } do
        if hasFS and isfile(path) then
            local chunk, err = loadstring(readfile(path), "@synchub")
            if not chunk then
                error("synchub.lua failed to compile: " .. tostring(err))
            end
            return chunk()
        end
    end

    local ok, body = pcall(function()
        return game:HttpGet(REPO .. "synchub.lua", true)
    end)
    if ok and type(body) == "string" and #body > 0 then
        local chunk, err = loadstring(body, "@synchub")
        if not chunk then
            error("synchub.lua from repo failed to compile: " .. tostring(err))
        end
        return chunk()
    end

    error("synchub.lua unavailable (no inline copy, no file, no network)")
end

local Hub = loadLibrary()
local win = Hub.new("SyncHub - Steal an Egg", DIR .. "/StealAnEgg")

--------------------------------------------------------------------- domain
-- Taken from your own config file, so the filter lists match what the game
-- actually uses rather than guesses.
local RARITIES = {
    "Common", "Uncommon", "Rare", "Epic", "Legendary",
    "Mythic", "Cosmic", "Divine", "Eternal", "Secret",
}
local AREAS = {
    "Cherry Blossom", "Cosmic", "Volcano", "Prehistoric", "Abyss Ocean",
}
local PRIORITIES = { "Rarity", "KG", "Nearest", "Value" }
local KG_MODES   = { "Any", "Above", "Below" }
local MOVE_MODES = { "Walk", "Glide", "Teleport" }
local ACTIONS    = {
    "Steal", "Place", "Hatch", "CollectCash", "OpenChest", "SkipChest",
    "SellPet", "SellEgg", "EquipBest", "UpgradePen", "Treadmill",
    "UpgradeTreadmill", "BuyTrail", "ClaimIndex", "HungryMonster",
}

--------------------------------------------------------------------- state
local State = {
    lp        = Players.LocalPlayer,
    session   = os.time(),
    steals    = 0,
    hatches   = 0,
    cash      = 0,
    lastSteal = 0,
    logging   = false,
    log       = {},        -- ordered list of unique captured calls
    logSeen   = {},        -- signature -> index
    esp       = {},        -- instance -> Highlight
    noclip    = false,
    hooked    = false,
}

local function lp() return State.lp end
local function char() return lp().Character end
local function root()
    local c = char()
    return c and (c:FindFirstChild("HumanoidRootPart") or c.PrimaryPart)
end
local function humanoid()
    local c = char()
    return c and c:FindFirstChildOfClass("Humanoid")
end

local function elapsed()
    local seconds = os.time() - State.session
    return string.format("%02d:%02d:%02d",
        seconds // 3600, (seconds % 3600) // 60, seconds % 60)
end

--=========================================================================--
--                                JOURNAL                                  --
--=========================================================================--
-- A kick tears down the Lua VM and takes any in-memory log with it, so every
-- notable action is appended to disk the moment it happens. After a kick, open
-- SyncHub/journal.txt: the last line is what the hub did immediately before.
local Journal = {}

function Journal:write(fmt, ...)
    local ok, body = pcall(string.format, fmt, ...)
    local line = string.format("[%s] %s", os.date("%H:%M:%S"),
        ok and body or tostring(fmt))

    if appendfile then
        pcall(appendfile, DIR .. "/journal.txt", line .. "\n")
    elseif hasFS and writefile then
        State.journalBuffer = (State.journalBuffer or "") .. line .. "\n"
        pcall(writefile, DIR .. "/journal.txt", State.journalBuffer)
    end
end

function Journal:reset()
    local header = string.format(
        "=== session %s | place %d | job %s | executor %s ===\n",
        os.date("%Y-%m-%d %H:%M:%S"), game.PlaceId, game.JobId,
        (identifyexecutor and identifyexecutor()) or "unknown")
    State.journalBuffer = header
    if hasFS and writefile then
        pcall(writefile, DIR .. "/journal.txt", header)
    end
end

--=========================================================================--
--                                ADAPTER                                  --
--=========================================================================--
-- Discovers the game's remotes and containers instead of assuming paths.
local Adapter = { remotes = {}, containers = {} }

local REMOTE_CLASSES = {
    RemoteEvent = true, RemoteFunction = true, UnreliableRemoteEvent = true,
}

function Adapter:scan()
    self.remotes, self.containers = {}, {}

    for _, service in { ReplicatedStorage, workspace } do
        local ok, descendants = pcall(function() return service:GetDescendants() end)
        if ok then
            for _, d in descendants do
                if REMOTE_CLASSES[d.ClassName] then
                    -- Keep the shortest path per name; games often mirror remotes.
                    local existing = self.remotes[d.Name]
                    if not existing or #d:GetFullName() < #existing:GetFullName() then
                        self.remotes[d.Name] = d
                    end
                end
            end
        end
    end

    -- Containers are matched loosely because names vary between updates.
    local wanted = {
        plots     = { "plot", "base", "pen", "island" },
        eggs      = { "egg" },
        conveyor  = { "conveyor", "belt" },
        chests    = { "chest" },
    }
    for _, child in workspace:GetChildren() do
        local lower = string.lower(child.Name)
        for slot, words in wanted do
            if not self.containers[slot] then
                for _, word in words do
                    if string.find(lower, word, 1, true) then
                        self.containers[slot] = child
                        break
                    end
                end
            end
        end
    end

    local count = 0
    for _ in self.remotes do count += 1 end
    return count
end

function Adapter:names()
    local names = {}
    for name in self.remotes do table.insert(names, name) end
    table.sort(names)
    return names
end

-- Resolves a binding saved in config into something callable.
-- A binding is { remote = "Name", method = "FireServer", args = { ... } }.
function Adapter:invoke(action, ...)
    local binding = win:Get("bind_" .. action)
    if type(binding) ~= "table" or not binding.remote then
        return false, "unbound"
    end

    local remote = self.remotes[binding.remote]
    if not remote then
        self:scan()
        remote = self.remotes[binding.remote]
    end
    if not remote then return false, "remote missing: " .. binding.remote end

    -- Saved args act as a template. Runtime args replace any "%s" placeholder,
    -- otherwise they are appended.
    local args = {}
    local runtime = { ... }
    local used = 0
    for i, value in binding.args or {} do
        if value == "%s" then
            used += 1
            args[i] = runtime[used]
        else
            args[i] = value
        end
    end
    for i = used + 1, #runtime do
        table.insert(args, runtime[i])
    end

    local method = binding.method == "InvokeServer" and "InvokeServer" or "FireServer"
    Journal:write("invoke %s -> %s:%s (%d args)", action, binding.remote,
        method, #args)
    local ok, result = pcall(function()
        return remote[method](remote, table.unpack(args))
    end)
    if not ok then
        Journal:write("invoke %s FAILED: %s", action, tostring(result))
    end
    return ok, result
end

function Adapter:bound(action)
    local binding = win:Get("bind_" .. action)
    return type(binding) == "table" and binding.remote ~= nil
end

--=========================================================================--
--                             REMOTE LOGGER                               --
--=========================================================================--
-- Hooks __namecall once and records outgoing FireServer/InvokeServer calls.
-- This is how you find the real "steal" remote: turn logging on, steal one egg
-- by hand, and the call shows up in the list ready to bind.
local Logger = {}

local function describeArg(value)
    local kind = typeof(value)
    if kind == "Instance" then
        return string.format("<%s:%s>", value.ClassName, value.Name)
    elseif kind == "table" then
        local ok, encoded = pcall(function() return HttpService:JSONEncode(value) end)
        return ok and encoded or "<table>"
    elseif kind == "string" then
        return string.format("%q", value)
    end
    return tostring(value)
end

local function signature(remoteName, method, args)
    local parts = { remoteName, method }
    for _, value in args do table.insert(parts, describeArg(value)) end
    return table.concat(parts, "|")
end

function Logger:record(remote, method, args)
    local sig = signature(remote.Name, method, args)
    local index = State.logSeen[sig]
    if index then
        State.log[index].hits += 1
        State.log[index].at = os.clock()
        return
    end

    -- Store a serialisable copy. Instances cannot go into a config file, so
    -- they are kept as live references for replay and as text for display.
    local template = {}
    for i, value in args do
        template[i] = typeof(value) == "Instance" and value or value
    end

    table.insert(State.log, {
        remote   = remote.Name,
        path     = remote:GetFullName(),
        method   = method,
        args     = template,
        display  = sig,
        hits     = 1,
        at       = os.clock(),
    })
    State.logSeen[sig] = #State.log
    win:Notify("logged " .. remote.Name, "ok", 2)
end

function Logger:install()
    if State.hooked then return true end
    if not (hookmetamethod and getnamecallmethod and checkcaller) then
        return false
    end

    local original
    original = hookmetamethod(game, "__namecall", function(instance, ...)
        if State.logging and not checkcaller() then
            local ok, method = pcall(getnamecallmethod)
            if ok and (method == "FireServer" or method == "InvokeServer")
                and REMOTE_CLASSES[instance.ClassName] then
                -- Varargs cannot cross into a nested closure, so capture first.
                local args = { ... }
                pcall(function() Logger:record(instance, method, args) end)
            end
        end
        return original(instance, ...)
    end)

    State.hooked = true
    return true
end

function Logger:dump()
    local lines = {}
    for i, entry in State.log do
        table.insert(lines, string.format("%2d. [%s] %s  hits=%d\n    %s",
            i, entry.method, entry.path, entry.hits, entry.display))
    end
    local report = table.concat(lines, "\n")
    if hasFS and writefile then
        pcall(writefile, DIR .. "/remotes.txt", report)
    end
    if setclipboard then pcall(setclipboard, report) end
    print(report)
    return report
end

-- Plot ownership is exposed differently per game version: sometimes an
-- attribute, sometimes a StringValue, sometimes a surface label. Try all three
-- and never let a missing one throw.
local function ownerOf(plot)
    local ok, value = pcall(function() return plot:GetAttribute("Owner") end)
    if ok and value ~= nil and value ~= "" then return tostring(value) end

    local holder = plot:FindFirstChild("Owner", true)
    if holder and holder:IsA("ValueBase") then
        local read, inner = pcall(function() return holder.Value end)
        if read and inner ~= nil and inner ~= "" then return tostring(inner) end
    end

    for _, d in plot:GetDescendants() do
        if d:IsA("TextLabel") then
            local name = string.match(d.Text, "^(%w+)'s")
            if name then return name end
        end
    end
    return nil
end

--=========================================================================--
--                             EGG INSPECTION                              --
--=========================================================================--
-- Reads whatever the game exposes about an egg. Attributes first, then value
-- objects, then the billboard text, because these games usually render the
-- rarity and weight above the egg even when they hide it from the client tree.
local function readInfo(model)
    local info = { name = model.Name, instance = model }

    local ok, attrs = pcall(function() return model:GetAttributes() end)
    if ok and type(attrs) == "table" then
        for rawKey, value in attrs do
            local key = string.lower(rawKey)
            if string.find(key, "rarity") then info.rarity = tostring(value)
            elseif string.find(key, "mutation") then info.mutation = tostring(value)
            elseif string.find(key, "kg") or string.find(key, "weight") then
                info.kg = tonumber(value) or info.kg
            elseif string.find(key, "area") or string.find(key, "biome") then
                info.area = tostring(value)
            elseif string.find(key, "eggname") or string.find(key, "display") then
                info.name = tostring(value)
            end
        end
    end

    for _, d in model:GetDescendants() do
        if d:IsA("ValueBase") then
            local key = string.lower(d.Name)
            local value = select(2, pcall(function() return d.Value end))
            if string.find(key, "rarity") then info.rarity = tostring(value)
            elseif string.find(key, "mutation") then info.mutation = tostring(value)
            elseif string.find(key, "kg") or string.find(key, "weight") then
                info.kg = tonumber(value) or info.kg
            end
        elseif d:IsA("TextLabel") and d.Text ~= "" then
            local text = d.Text
            local kg = string.match(text, "([%d%.]+)%s*[kK][gG]")
            if kg then info.kg = tonumber(kg) or info.kg end
            for _, rarity in RARITIES do
                if string.find(text, rarity, 1, true) then info.rarity = rarity end
            end
        end
    end

    return info
end

-- True when the egg passes every filter the user has switched on.
local function matchesFilter(info)
    local rarities = win:Get("TargetRarities")
    if type(rarities) == "table" and next(rarities) then
        if not (info.rarity and rarities[info.rarity]) then return false end
    end

    local areas = win:Get("TargetAreas")
    if type(areas) == "table" and next(areas) and info.area then
        if not areas[info.area] then return false end
    end

    local mode = win:Get("TargetKGMode", "Any")
    local threshold = tonumber(win:Get("TargetKGThreshold", 0)) or 0
    if mode ~= "Any" and threshold > 0 then
        local kg = info.kg or 0
        if mode == "Above" and kg < threshold then return false end
        if mode == "Below" and kg > threshold then return false end
    end

    return true
end

local RARITY_RANK = {}
for index, rarity in RARITIES do RARITY_RANK[rarity] = index end

local function scoreOf(info, origin)
    local priority = win:Get("TargetPriority", "Rarity")
    if priority == "KG" then
        return info.kg or 0
    elseif priority == "Nearest" then
        local part = info.instance:IsA("BasePart") and info.instance
            or info.instance:FindFirstChildWhichIsA("BasePart")
        if not part or not origin then return -math.huge end
        return -(part.Position - origin).Magnitude
    elseif priority == "Value" then
        return (RARITY_RANK[info.rarity] or 0) * 1000 + (info.kg or 0)
    end
    return RARITY_RANK[info.rarity] or 0
end

--=========================================================================--
--                                FEATURES                                 --
--=========================================================================--
local Features = {}

------------------------------------------------------------------- movement
function Features.applyCharacter()
    local hum = humanoid()
    if not hum then return end
    local speed = tonumber(win:Get("WalkSpeed", 16)) or 16
    local jump  = tonumber(win:Get("JumpPower", 50)) or 50
    pcall(function()
        hum.WalkSpeed = speed
        hum.UseJumpPower = true
        hum.JumpPower = jump
    end)
end

function Features.noclip(on)
    State.noclip = on
    if on and not State.noclipConn then
        State.noclipConn = win:Track(RunService.Stepped:Connect(function()
            local c = char()
            if not c then return end
            for _, part in c:GetDescendants() do
                if part:IsA("BasePart") and part.CanCollide then
                    part.CanCollide = false
                end
            end
        end))
    elseif not on and State.noclipConn then
        State.noclipConn:Disconnect()
        State.noclipConn = nil
    end
end

function Features.infiniteJump(on)
    if on and not State.jumpConn then
        local UIS = game:GetService("UserInputService")
        State.jumpConn = win:Track(UIS.JumpRequest:Connect(function()
            local hum = humanoid()
            if hum then hum:ChangeState(Enum.HumanoidStateType.Jumping) end
        end))
    elseif not on and State.jumpConn then
        State.jumpConn:Disconnect()
        State.jumpConn = nil
    end
end

-- Three ways to reach a target, in ascending order of how obvious each is to a
-- server-side check:
--   Walk     - Humanoid:MoveTo. Real pathing, real physics, nothing to detect.
--   Glide    - small per-frame CFrame nudges, hard capped so no single step
--              exceeds what a fast legitimate player covers in one frame.
--   Teleport - one jump straight to the target. Fastest and loudest.
-- Walk is the default on purpose. Teleport at 900+ studs/sec is the single most
-- reliable way to get kicked from a game like this.
local ARRIVE   = 7    -- studs; close enough to interact
local MAX_STEP = 18   -- studs per frame ceiling in Glide mode

function Features.moveTo(position, speed, mode)
    local part = root()
    if not part then return false end

    mode  = mode or win:Get("StealMode", "Walk")
    speed = math.max(tonumber(speed) or 120, 16)
    local deadline = os.clock() + (tonumber(win:Get("MoveTimeout", 20)) or 20)
    local distance = (position - part.Position).Magnitude

    if mode == "Teleport" then
        Journal:write("teleport %.0f studs", distance)
        part.CFrame = CFrame.new(position + Vector3.new(0, 3, 0))
            * (part.CFrame - part.Position)
        return true
    end

    if mode == "Walk" then
        local hum = humanoid()
        if not hum then return false end
        Journal:write("walk %.0f studs", distance)
        while os.clock() < deadline do
            part = root()
            if not part then return false end
            if (position - part.Position).Magnitude < ARRIVE then return true end
            hum:MoveTo(position)   -- re-issued because MoveTo gives up after 8s
            task.wait(0.25)
        end
        Journal:write("walk timed out")
        return false
    end

    Journal:write("glide %.0f studs at %d", distance, speed)
    while os.clock() < deadline do
        part = root()
        if not part then return false end
        local offset = position - part.Position
        if offset.Magnitude < ARRIVE then return true end
        local dt = RunService.Heartbeat:Wait()
        local step = math.min(offset.Magnitude, speed * dt, MAX_STEP)
        local rotation = part.CFrame - part.Position
        part.CFrame = CFrame.new(part.Position + offset.Unit * step) * rotation
    end
    Journal:write("glide timed out")
    return false
end

---------------------------------------------------------------- performance
local STRIP = {
    ParticleEmitter = true, Trail = true, Smoke = true, Fire = true,
    Sparkles = true, Explosion = true, Beam = true,
}
local POST = {
    BloomEffect = true, BlurEffect = true, SunRaysEffect = true,
    DepthOfFieldEffect = true, ColorCorrectionEffect = true,
}

function Features.extremeFPS()
    pcall(function()
        settings().Rendering.QualityLevel = Enum.QualityLevel.Level01
    end)
    pcall(function()
        Lighting.GlobalShadows = false
        Lighting.FogEnd = 1e6
        workspace.Terrain.WaterWaveSize = 0
        workspace.Terrain.WaterWaveSpeed = 0
        workspace.Terrain.WaterReflectance = 0
        workspace.Terrain.WaterTransparency = 0
    end)
    for _, fx in Lighting:GetChildren() do
        if POST[fx.ClassName] then pcall(function() fx.Enabled = false end) end
    end

    local seen = 0
    for _, inst in workspace:GetDescendants() do
        seen += 1
        if seen % 600 == 0 then task.wait() end   -- keep the frame alive on mobile
        local class = inst.ClassName
        if STRIP[class] then
            pcall(function() inst.Enabled = false end)
        elseif class == "MeshPart" then
            pcall(function()
                inst.RenderFidelity = Enum.RenderFidelity.Performance
            end)
        elseif inst:IsA("BasePart") then
            pcall(function()
                inst.Material = Enum.Material.SmoothPlastic
                inst.Reflectance = 0
                inst.CastShadow = false
            end)
        end
    end
    win:Notify(string.format("render sweep: %d objects", seen), "ok")
end

function Features.tickRate(on)
    if setfpscap then pcall(setfpscap, on and 240 or 60) end
end

function Features.blackScreen(on)
    if on then
        if not State.blackout then
            State.blackout = Hub.create("Frame", {
                Name = "Blackout", Size = UDim2.fromScale(1, 1),
                BackgroundColor3 = Color3.new(), BorderSizePixel = 0,
                ZIndex = -10,
            }, win.gui)
        end
        State.blackout.Visible = true
    elseif State.blackout then
        State.blackout.Visible = false
    end
end

-- Pets are the heaviest thing on screen in these games; hiding them is the
-- single biggest client-side win after the render sweep.
function Features.hidePets(on)
    local plots = Adapter.containers.plots
    if not plots then return end
    for _, d in plots:GetDescendants() do
        local lower = string.lower(d.Name)
        if string.find(lower, "pet", 1, true) and d:IsA("BasePart") then
            pcall(function() d.Transparency = on and 1 or 0 end)
        end
    end
end

------------------------------------------------------------------------ esp
local function clearESP()
    for inst, highlight in State.esp do
        pcall(function() highlight:Destroy() end)
        State.esp[inst] = nil
    end
end

local function markESP(model, text, colour)
    if State.esp[model] then
        local existing = State.esp[model]:FindFirstChild("Tag")
        if existing then
            local body = existing:FindFirstChildWhichIsA("TextLabel")
            if body then body.Text = text end
        end
        return
    end

    local highlight = Instance.new("Highlight")
    highlight.FillColor = colour
    highlight.FillTransparency = 0.55
    highlight.OutlineColor = colour
    highlight.DepthMode = Enum.HighlightDepthMode.AlwaysOnTop
    highlight.Adornee = model
    highlight.Parent = win.gui

    local billboard = Instance.new("BillboardGui")
    billboard.Name = "Tag"
    billboard.Adornee = model:IsA("Model")
        and (model.PrimaryPart or model:FindFirstChildWhichIsA("BasePart"))
        or model
    billboard.Size = UDim2.fromOffset(170, 30)
    billboard.StudsOffset = Vector3.new(0, 2.5, 0)
    billboard.AlwaysOnTop = true
    billboard.Parent = highlight

    local body = Instance.new("TextLabel")
    body.BackgroundTransparency = 1
    body.Size = UDim2.fromScale(1, 1)
    body.Font = Enum.Font.GothamBold
    body.TextSize = 12
    body.TextColor3 = colour
    body.TextStrokeTransparency = 0.4
    body.Text = text
    body.Parent = billboard

    State.esp[model] = highlight
end

local RARITY_COLOUR = {
    Common = Color3.fromRGB(180, 185, 195),
    Uncommon = Color3.fromRGB(120, 210, 130),
    Rare = Color3.fromRGB(90, 160, 235),
    Epic = Color3.fromRGB(175, 120, 235),
    Legendary = Color3.fromRGB(240, 190, 80),
    Mythic = Color3.fromRGB(235, 110, 110),
    Cosmic = Color3.fromRGB(140, 240, 235),
    Divine = Color3.fromRGB(255, 245, 170),
    Eternal = Color3.fromRGB(255, 140, 220),
    Secret = Color3.fromRGB(255, 255, 255),
}

function Features.refreshESP()
    local wantEggs = win:Get("EggESP") == true
    local wantPens = win:Get("PenESP") == true

    if not wantEggs and not wantPens then
        clearESP()
        return
    end

    local live = {}

    if wantEggs then
        local areaFilter = win:Get("EggESPAreas")
        for _, model in Features.eggs() do
            local info = readInfo(model)
            local pass = true
            if type(areaFilter) == "table" and next(areaFilter) and info.area then
                pass = areaFilter[info.area] == true
            end
            if pass then
                live[model] = true
                local bits = { info.name }
                if info.rarity then table.insert(bits, info.rarity) end
                if info.kg then table.insert(bits, string.format("%.1fkg", info.kg)) end
                markESP(model, table.concat(bits, " | "),
                    RARITY_COLOUR[info.rarity] or Hub.THEME.accent)
            end
        end
    end

    if wantPens then
        local plots = Adapter.containers.plots
        if plots then
            for _, plot in plots:GetChildren() do
                local owner = ownerOf(plot)
                if owner then
                    live[plot] = true
                    markESP(plot, "Pen: " .. tostring(owner), Hub.THEME.warn)
                end
            end
        end
    end

    for model, highlight in State.esp do
        if not live[model] or not model.Parent then
            pcall(function() highlight:Destroy() end)
            State.esp[model] = nil
        end
    end
end

-- Every model in the game that looks like an egg, excluding your own pen.
function Features.eggs()
    local found = {}
    local source = Adapter.containers.eggs or Adapter.containers.plots or workspace
    local myName = lp().Name

    local ok, descendants = pcall(function() return source:GetDescendants() end)
    if not ok then return found end

    for _, d in descendants do
        if d:IsA("Model") and string.find(string.lower(d.Name), "egg", 1, true) then
            local full = d:GetFullName()
            if not string.find(full, myName, 1, true) then
                table.insert(found, d)
            end
        end
    end
    return found
end

------------------------------------------------------------------- anti afk
function Features.antiAFK(on)
    if on and not State.afkConn then
        State.afkConn = win:Track(lp().Idled:Connect(function()
            pcall(function()
                VirtualUser:CaptureController()
                VirtualUser:ClickButton2(Vector2.new())
            end)
        end))
    elseif not on and State.afkConn then
        State.afkConn:Disconnect()
        State.afkConn = nil
    end
end

-------------------------------------------------------------------- webhook
local webhookQueue, webhookBusy = {}, false

local function httpPost(url, body)
    local request = ENV.request or ENV.http_request
        or (ENV.syn and ENV.syn.request)
    if not request then return false, "no request function" end
    local ok, response = pcall(request, {
        Url = url,
        Method = "POST",
        Headers = { ["Content-Type"] = "application/json" },
        Body = HttpService:JSONEncode(body),
    })
    if not ok then return false, tostring(response) end
    local status = tonumber(response.StatusCode or response.Status) or 0
    return status >= 200 and status < 300, status
end

-- Discord rate limits hard, so posts are queued and drained one per second.
function Features.webhook(title, description, colour)
    local url = win:Get("WebhookURL", "")
    if type(url) ~= "string" or not string.find(url, "discord", 1, true) then
        return
    end

    table.insert(webhookQueue, {
        embeds = {{
            title = title,
            description = description,
            color = colour or 0x58D68D,
            footer = { text = "SyncHub - " .. lp().Name },
            timestamp = DateTime.now():ToIsoDate(),
        }},
    })

    if webhookBusy then return end
    webhookBusy = true
    task.spawn(function()
        while #webhookQueue > 0 do
            local payload = table.remove(webhookQueue, 1)
            httpPost(url, payload)
            task.wait(1.1)
        end
        webhookBusy = false
    end)
end

--------------------------------------------------------------------- server
-- A teleport tears down the Lua VM, so the hub dies on rejoin and on every
-- server hop unless the executor is told to run it again on the other side.
local RELOAD = 'loadstring(game:HttpGet("' .. REPO .. 'sae.lua"))()'

local function persistThroughTeleport()
    local queue = ENV.queue_on_teleport or queue_on_teleport
    if not queue then
        win:Notify("executor has no queue_on_teleport - reload manually "
            .. "after the hop", "warn", 6)
        return false
    end
    local ok = pcall(queue, RELOAD)
    return ok
end

function Features.rejoin()
    persistThroughTeleport()
    if #Players:GetPlayers() <= 1 then
        pcall(function() TeleportService:Teleport(game.PlaceId, lp()) end)
    else
        pcall(function()
            TeleportService:TeleportToPlaceInstance(game.PlaceId, game.JobId, lp())
        end)
    end
end

function Features.serverHop()
    local url = string.format(
        "https://games.roblox.com/v1/games/%d/servers/Public?sortOrder=Asc&limit=100",
        game.PlaceId)

    local ok, body = pcall(function() return game:HttpGet(url) end)
    if not ok then return win:Notify("hop failed: http", "bad") end

    local decoded, payload = pcall(function() return HttpService:JSONDecode(body) end)
    if not decoded or type(payload.data) ~= "table" then
        return win:Notify("hop failed: parse", "bad")
    end

    for _, server in payload.data do
        if server.id ~= game.JobId and server.playing < server.maxPlayers then
            win:Notify("hopping...", "warn")
            persistThroughTeleport()
            local sent = pcall(function()
                TeleportService:TeleportToPlaceInstance(game.PlaceId, server.id, lp())
            end)
            if sent then return end
        end
    end
    win:Notify("no open server found", "bad")
end

--=========================================================================--
--                               AUTOMATION                                --
--=========================================================================--
-- Your own pen, found by owner attribute rather than by index, because plot
-- numbering is not stable across servers.
function Features.myPen()
    local plots = Adapter.containers.plots
    if not plots then return nil end
    local myName = lp().Name
    for _, plot in plots:GetChildren() do
        if ownerOf(plot) == myName then return plot end
    end
    return nil
end

local function pivotOf(model)
    if not model then return nil end
    if model:IsA("BasePart") then return model.Position end
    local ok, pivot = pcall(function() return model:GetPivot().Position end)
    if ok then return pivot end
    local part = model:FindFirstChildWhichIsA("BasePart")
    return part and part.Position or nil
end

local function nearTrap(position)
    if win:Get("PreventTraps") ~= true then return false end
    local plots = Adapter.containers.plots
    if not plots or not position then return false end
    for _, d in plots:GetDescendants() do
        if d:IsA("BasePart") then
            local lower = string.lower(d.Name)
            if string.find(lower, "trap", 1, true)
                or string.find(lower, "guard", 1, true) then
                if (d.Position - position).Magnitude < 12 then return true end
            end
        end
    end
    return false
end

-- One steal attempt: pick the best egg that passes the filter, go to it, fire
-- the bound remote, come home.
function Features.stealOnce()
    if not Adapter:bound("Steal") then
        win:Notify("Steal is unbound - see the REMOTES tab", "warn", 5)
        return false
    end

    local origin = pivotOf(char())
    local best, bestScore = nil, -math.huge

    for _, model in Features.eggs() do
        local info = readInfo(model)
        if matchesFilter(info) then
            local position = pivotOf(model)
            if position and not nearTrap(position) then
                local score = scoreOf(info, origin)
                if score > bestScore then
                    best, bestScore = info, score
                end
            end
        end
    end

    if not best then return false end

    local home = pivotOf(Features.myPen())
    local target = pivotOf(best.instance)
    if not target then return false end

    Features.moveTo(target, win:Get("StealSpeed", 120))
    local ok = Adapter:invoke("Steal", best.instance)

    if ok then
        State.steals += 1
        State.lastSteal = os.time()
        if win:Get("WebhookSteals") == true then
            Features.webhook("Egg stolen", string.format(
                "**%s**\nRarity: %s\nWeight: %s kg\nTotal this session: %d",
                best.name, tostring(best.rarity or "?"),
                tostring(best.kg or "?"), State.steals))
        end
    end

    if home then Features.moveTo(home, win:Get("StealSpeed", 120)) end
    return ok
end

-- Most automations are "fire this remote on a timer". One helper covers them
-- all, so adding a new one is a single line in the UI section.
local function simpleWorker(idx, action, interval)
    local warned = false
    win:Loop(interval, function()
        if not Adapter:bound(action) then
            if not warned then
                warned = true
                win:Notify(action .. " is unbound", "warn", 4)
            end
            return
        end
        warned = false
        Adapter:invoke(action)
    end, function()
        return win:Get(idx) == true
    end)
end

--=========================================================================--
--                                   UI                                    --
--=========================================================================--
local tabHome     = win:Tab("HOME")
local tabEggs     = win:Tab("EGGS")
local tabProgress = win:Tab("PROGRESS")
local tabSell     = win:Tab("SELL")
local tabRemotes  = win:Tab("REMOTES")
local tabSettings = win:Tab("SETTINGS")
local tabWebhook  = win:Tab("WEBHOOK")

------------------------------------------------------------------------ home
do
    local session = tabHome:Group("Session")
    local statLines = {
        session:Label("uptime: 00:00:00"),
        session:Label("steals: 0"),
        session:Label("eggs visible: 0"),
        session:Label("remotes found: 0"),
    }

    win:Loop(1, function()
        statLines[1].Set("uptime: " .. elapsed())
        statLines[2].Set(string.format("steals: %d   hatches: %d",
            State.steals, State.hatches))
        statLines[3].Set("eggs visible: " .. #Features.eggs())

        local count = 0
        for _ in Adapter.remotes do count += 1 end
        statLines[4].Set("remotes found: " .. count)

        if win:Get("ShowStatusOverlay") == true then
            win:OverlaySet("up", "uptime " .. elapsed())
            win:OverlaySet("steal", "steals " .. State.steals)
            win:OverlaySet("ping", string.format("players %d/%d",
                #Players:GetPlayers(), Players.MaxPlayers))
        end
    end)

    local server = tabHome:Group("Server")
    server:Button("Rejoin", Features.rejoin)
    server:Button("Server hop", Features.serverHop)
    server:Button("Copy JobId", function()
        if setclipboard then setclipboard(game.JobId) end
        win:Notify("JobId copied", "ok")
    end)
    server:Button("Rescan remotes", function()
        win:Notify(Adapter:scan() .. " remotes found", "ok")
    end)
    server:Button("Unload hub", function() win:Destroy() end)
end

------------------------------------------------------------------------ eggs
do
    local filter = tabEggs:Group("Steal filter")
    filter:Dropdown("TargetRarities", "Rarities", RARITIES, {}, true)
    filter:Dropdown("TargetAreas", "Areas", AREAS, {}, true)
    filter:Dropdown("TargetPriority", "Priority", PRIORITIES, "Rarity")
    filter:Dropdown("TargetKGMode", "Weight mode", KG_MODES, "Any")
    filter:Slider("TargetKGThreshold", "Weight threshold", 0, 100, 0, 1)

    local steal = tabEggs:Group("Auto steal")
    steal:Toggle("AutoSteal", "Auto steal", false)
    steal:Toggle("PersistentSteal", "Retry on failure", true)
    steal:Toggle("PreventTraps", "Avoid traps and guards", true)
    steal:Dropdown("StealMode", "Travel mode", MOVE_MODES, "Walk")
    steal:Label("Walk is real movement and cannot be detected. Glide is "
        .. "capped per frame. Teleport is fast and the most likely to get "
        .. "you kicked.")
    steal:Slider("StealSpeed", "Glide speed", 40, 400, 120, 10)
    steal:Slider("StealDelay", "Delay between steals", 0.5, 15, 3, 0.5)
    steal:Slider("MoveTimeout", "Give up after", 5, 60, 20, 1)
    steal:Button("Steal once (test)", function()
        local ok = Features.stealOnce()
        win:Notify(ok and "steal fired" or "no valid target", ok and "ok" or "warn")
    end)

    local place = tabEggs:Group("Auto place / hatch", true)
    place:Toggle("AutoPlace", "Auto place eggs", false)
    place:Toggle("AutoHatch", "Auto hatch", false)
    place:Slider("HatchInterval", "Hatch interval", 0.5, 30, 2, 0.5)

    -- The steal loop is hand written because it has real logic; everything
    -- else on this tab is a timed remote call.
    win:Loop(0.1, function()
        local ok = Features.stealOnce()
        if not ok and win:Get("PersistentSteal") ~= true then
            task.wait(2)
        end
        task.wait(tonumber(win:Get("StealDelay", 1)) or 1)
    end, function()
        return win:Get("AutoSteal") == true
    end)

    simpleWorker("AutoPlace", "Place", 1.5)
    win:Loop(0.5, function()
        Adapter:invoke("Hatch")
        State.hatches += 1
        if win:Get("WebhookHatches") == true then
            Features.webhook("Egg hatched", "Session total: " .. State.hatches)
        end
        task.wait(tonumber(win:Get("HatchInterval", 2)) or 2)
    end, function()
        return win:Get("AutoHatch") == true and Adapter:bound("Hatch")
    end)
end

-------------------------------------------------------------------- progress
do
    local cash = tabProgress:Group("Economy")
    cash:Toggle("AutoCollectCash", "Auto collect cash", true)
    cash:Toggle("AutoOpenChest", "Auto open chests", true)
    cash:Toggle("AutoSkipChest", "Auto skip chest timer", true)
    cash:Toggle("AutoClaimIndex", "Auto claim index rewards", true)

    local pets = tabProgress:Group("Pets")
    pets:Toggle("AutoEquipBest", "Equip best pets", true)
    pets:Slider("EquipInterval", "Equip interval", 5, 300, 30, 5)

    local upgrades = tabProgress:Group("Upgrades")
    upgrades:Toggle("AutoUpgradePen", "Auto upgrade pen", true)
    upgrades:Toggle("AutoTreadmill", "Auto treadmill", true)
    upgrades:Toggle("AutoUpgradeTreadmill", "Auto upgrade treadmill", true)
    upgrades:Toggle("AutoBuyTrail", "Auto buy trail", false)

    local event = tabProgress:Group("Event")
    event:Toggle("AutoHungryMonster", "Auto hungry monster", false)
    event:Label("Feeds the monster with anything not protected below.")
    event:Dropdown("MonsterProtected", "Never feed", RARITIES,
        { Divine = true, Eternal = true, Secret = true }, true)

    simpleWorker("AutoCollectCash", "CollectCash", 1)
    simpleWorker("AutoOpenChest", "OpenChest", 2)
    simpleWorker("AutoSkipChest", "SkipChest", 2)
    simpleWorker("AutoClaimIndex", "ClaimIndex", 10)
    simpleWorker("AutoUpgradePen", "UpgradePen", 5)
    simpleWorker("AutoTreadmill", "Treadmill", 3)
    simpleWorker("AutoUpgradeTreadmill", "UpgradeTreadmill", 8)
    simpleWorker("AutoBuyTrail", "BuyTrail", 15)
    simpleWorker("AutoHungryMonster", "HungryMonster", 4)

    win:Loop(1, function()
        Adapter:invoke("EquipBest")
        task.wait(tonumber(win:Get("EquipInterval", 30)) or 30)
    end, function()
        return win:Get("AutoEquipBest") == true and Adapter:bound("EquipBest")
    end)
end

------------------------------------------------------------------------ sell
do
    local pets = tabSell:Group("Sell pets")
    pets:Toggle("AutoSellPets", "Auto sell pets", false)
    pets:Toggle("SellPetsWhenFull", "Only when inventory full", false)
    pets:Dropdown("SellRarities", "Rarities to sell", RARITIES, {}, true)
    pets:Dropdown("SellPetKGMode", "Weight mode", KG_MODES, "Any")
    pets:Slider("SellPetKGThreshold", "Weight threshold", 0, 100, 0, 1)

    local eggs = tabSell:Group("Sell eggs")
    eggs:Toggle("AutoSellEggs", "Auto sell eggs", false)
    eggs:Toggle("SellEggsWhenFull", "Only when inventory full", false)
    eggs:Dropdown("SellEggRarities", "Rarities to sell", RARITIES, {}, true)
    eggs:Slider("SellEggKGThreshold", "Weight threshold", 0, 100, 0, 1)

    simpleWorker("AutoSellPets", "SellPet", 5)
    simpleWorker("AutoSellEggs", "SellEgg", 5)
end

--------------------------------------------------------------------- remotes
do
    local capture = tabRemotes:Group("Remote logger")
    capture:Label("1. Turn logging on. 2. Do the action once by hand. "
        .. "3. Dump the log and note the number. 4. Bind it below.")
    capture:Toggle("RemoteLogging", "Log outgoing remotes", false, function(on)
        State.logging = on
        if on and not Logger:install() then
            win:Notify("executor lacks hookmetamethod", "bad", 6)
        end
    end)
    capture:Button("Dump log to file + clipboard", function()
        if #State.log == 0 then return win:Notify("log is empty", "warn") end
        Logger:dump()
        win:Notify(#State.log .. " calls written to " .. DIR .. "/remotes.txt", "ok")
    end)
    capture:Button("Clear log", function()
        State.log, State.logSeen = {}, {}
        win:Notify("log cleared", "ok")
    end)

    local bind = tabRemotes:Group("Bind a call to an action")
    bind:Dropdown("BindAction", "Action", ACTIONS, "Steal")
    bind:Input("BindIndex", "Log entry number", "1")
    bind:Button("Bind", function()
        local action = win:Get("BindAction", "Steal")
        local index = tonumber(win:Get("BindIndex", "1"))
        local entry = index and State.log[index]
        if not entry then return win:Notify("no log entry " .. tostring(index), "bad") end

        -- Instance arguments are stored as a marker so the automation can
        -- substitute a live target at call time.
        local args = {}
        for i, value in entry.args do
            args[i] = typeof(value) == "Instance" and "%s" or value
        end

        win:Set("bind_" .. action, {
            remote = entry.remote,
            method = entry.method,
            args   = args,
        })
        win:Notify(action .. " -> " .. entry.remote, "ok", 5)
    end)
    bind:Button("Show current bindings", function()
        local lines = {}
        for _, action in ACTIONS do
            local binding = win:Get("bind_" .. action)
            table.insert(lines, string.format("%-18s %s", action,
                type(binding) == "table" and binding.remote or "-"))
        end
        local report = table.concat(lines, "\n")
        print(report)
        if setclipboard then setclipboard(report) end
        win:Notify("bindings printed to console", "ok")
    end)
    bind:Button("Clear all bindings", function()
        for _, action in ACTIONS do win:Set("bind_" .. action, nil) end
        win:Notify("bindings cleared", "warn")
    end)
end

-------------------------------------------------------------------- settings
do
    local movement = tabSettings:Group("Movement")
    movement:Slider("WalkSpeed", "Walk speed", 16, 120, 16, 1, Features.applyCharacter)
    movement:Slider("JumpPower", "Jump power", 50, 150, 50, 5, Features.applyCharacter)
    movement:Toggle("Noclip", "Noclip", false, Features.noclip)
    movement:Toggle("InfiniteJump", "Infinite jump", false, Features.infiniteJump)
    movement:Label("Walk speed above about 40 and noclip are what simple "
        .. "anti-cheats look for. Raise them a little at a time.")

    local perf = tabSettings:Group("Performance")
    perf:Toggle("ExtremeFPS", "Extreme FPS mode", false, function(on)
        if on then task.spawn(Features.extremeFPS) end
    end)
    perf:Toggle("BoostTickRate", "Uncap FPS", false, Features.tickRate)
    perf:Toggle("HidePets", "Hide pets", false, Features.hidePets)
    perf:Toggle("BlackScreen", "Black screen", false, Features.blackScreen)
    perf:Button("Run render sweep now", function()
        task.spawn(Features.extremeFPS)
    end)

    local esp = tabSettings:Group("ESP")
    esp:Toggle("EggESP", "Egg ESP", false)
    esp:Toggle("PenESP", "Pen ESP", false)
    esp:Dropdown("EggESPAreas", "Only these areas", AREAS, {}, true)
    esp:Slider("ESPRefresh", "Refresh rate", 0.2, 5, 1, 0.1)

    local misc = tabSettings:Group("Misc")
    misc:Toggle("AntiAFK", "Anti AFK", true, Features.antiAFK)
    misc:Toggle("ShowStatusOverlay", "Status overlay", true, function(on)
        win:Overlay(on)
    end)
    misc:Keybind("MenuKey", "Toggle menu", Enum.KeyCode.RightShift, function()
        win:ToggleVisible()
    end)

    local config = tabSettings:Group("Config")
    config:Input("ConfigName", "Config name", "default")
    config:Button("Save", function()
        win:SaveConfig(win:Get("ConfigName", "default"))
    end)
    config:Button("Load", function()
        win:LoadConfig(win:Get("ConfigName", "default"))
    end)
    config:Button("List saved configs", function()
        local names = win:ListConfigs()
        win:Notify(#names > 0 and table.concat(names, ", ") or "none saved", "ok", 6)
    end)

    win:Loop(1, function()
        Features.refreshESP()
        task.wait(tonumber(win:Get("ESPRefresh", 1)) or 1)
    end, function()
        return win:Get("EggESP") == true or win:Get("PenESP") == true
    end)
end

--------------------------------------------------------------------- webhook
do
    local hook = tabWebhook:Group("Webhook")
    hook:Input("WebhookURL", "Discord webhook URL", "")
    hook:Button("Send test message", function()
        Features.webhook("SyncHub online",
            string.format("Player: %s\nServer: %d players", lp().Name,
                #Players:GetPlayers()))
        win:Notify("test queued", "ok")
    end)

    local alerts = tabWebhook:Group("Alerts")
    alerts:Toggle("WebhookSteals", "On steal", false)
    alerts:Toggle("WebhookHatches", "On hatch", false)
    alerts:Toggle("WebhookDisconnects", "On disconnect", false)
    alerts:Toggle("WebhookInventoryFull", "On inventory full", false)
    alerts:Label("The URL stays in your local config and is only ever "
        .. "posted to Discord.")
end

--=========================================================================--
--                                  BOOT                                   --
--=========================================================================--
local found = Adapter:scan()

Journal:reset()
Journal:write("boot: %d remotes, hook=%s, queue_on_teleport=%s",
    found, tostring(hookmetamethod ~= nil),
    tostring((ENV.queue_on_teleport or queue_on_teleport) ~= nil))

win:Track(lp().CharacterAdded:Connect(function()
    task.wait(0.6)
    Journal:write("respawn")
    Features.applyCharacter()
    if State.noclip then Features.noclip(true) end
end))

if win:Get("ShowStatusOverlay") ~= false then win:Overlay(true) end

-- Re-scan periodically: streaming and round resets add remotes after join.
win:Loop(30, function() Adapter:scan() end)

win:Select("HOME")
win:SetStatus(string.format("%d remotes | %s", found,
    (hookmetamethod and "hook ok") or "no hook"), Hub.THEME.accent)

win:Notify(string.format("SyncHub ready. %d remotes discovered.", found), "ok", 5)
if not hookmetamethod then
    win:Notify("This executor cannot log remotes. Automation will need "
        .. "manual bindings.", "warn", 8)
end

win.onDestroy = function()
    State.logging = false
    clearESP()
    Features.noclip(false)
    Features.blackScreen(false)
end

return win



-- ==== end steal_an_egg.lua ===============================================